"use client";
import { CheckCircle2, KeyRound, Monitor, SlidersHorizontal } from "lucide-react";
import { useEffect, useState } from "react";
import { Alert,AlertDescription,AlertTitle } from "@/components/ui/alert";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card,CardContent,CardDescription,CardHeader,CardTitle } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Separator } from "@/components/ui/separator";
import { Switch } from "@/components/ui/switch";
export default function SettingsPage(){const [compact,setCompact]=useState(false);const [saved,setSaved]=useState(false);useEffect(()=>setCompact(localStorage.getItem("cp-compact")==="true"),[]);const save=()=>{localStorage.setItem("cp-compact",String(compact));setSaved(true);setTimeout(()=>setSaved(false),1800)};return <div className="grid gap-6 xl:grid-cols-2"><Card><CardHeader><CardTitle className="flex items-center gap-2"><KeyRound className="size-4"/>AI 设置</CardTitle><CardDescription>没有 API Key 也可以正常计算利润。</CardDescription></CardHeader><CardContent><Alert className="bg-emerald-50"><CheckCircle2 className="size-4 text-emerald-600"/><AlertTitle>Rules Mode · System Ready</AlertTitle><AlertDescription>当前使用规则识别模式；财务计算始终在确定性 Python 引擎中完成。</AlertDescription></Alert><label className="mt-5 block space-y-2 text-sm"><span>OpenAI API Key</span><Input type="password" disabled placeholder="请在后端 .env 中配置 OPENAI_API_KEY"/></label><p className="mt-2 text-xs text-slate-500">为避免浏览器泄露密钥，API Key 只允许通过服务端环境变量配置。</p></CardContent></Card><Card><CardHeader><CardTitle className="flex items-center gap-2"><SlidersHorizontal className="size-4"/>利润判断阈值</CardTitle><CardDescription>当前后端配置，只读展示。</CardDescription></CardHeader><CardContent className="space-y-3">{[["强烈推荐","≥ 20%","bg-emerald-500"],["可以参加","10%–20%","bg-green-500"],["谨慎参加","3%–10%","bg-amber-500"],["不建议参加","0%–3%","bg-orange-500"],["明确亏损","< 0%","bg-red-500"]].map(x=><div key={x[0]} className="flex items-center justify-between rounded-lg border p-3 text-sm"><span className="flex items-center gap-2"><span className={`size-2 rounded-full ${x[2]}`}/>{x[0]}</span><Badge variant="outline">{x[1]}</Badge></div>)}</CardContent></Card><Card><CardHeader><CardTitle>平台默认参数</CardTitle><CardDescription>TikTok Shop、Amazon、Temu 与 SHEIN。</CardDescription></CardHeader><CardContent><Alert><AlertTitle>DEMO DEFAULT</AlertTitle><AlertDescription>默认费率不是平台当前官方费率，会随国家、站点、类目和卖家协议变化。请在商品管理中覆盖实际费率。</AlertDescription></Alert></CardContent></Card><Card><CardHeader><CardTitle className="flex items-center gap-2"><Monitor className="size-4"/>显示设置</CardTitle><CardDescription>比赛默认使用浅色模式。</CardDescription></CardHeader><CardContent><div className="flex items-center justify-between"><div><p className="text-sm font-medium">紧凑数据密度</p><p className="mt-1 text-xs text-slate-500">偏好保存在当前浏览器。</p></div><Switch checked={compact} onCheckedChange={setCompact}/></div><Separator className="my-5"/><Button onClick={save}>{saved?"已保存":"保存显示设置"}</Button></CardContent></Card></div>}

