"use client";

import { useEffect, useState } from "react";
import { api } from "@/lib/api";
import translations from "@/lib/auto-translations.json";
import { useAuth } from "@/components/auth-provider";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Input } from "@/components/ui/input";

const fields = ["order_id", "sku", "settled_at", "currency", "gross_revenue", "quantity", "refund_amount", "subsidy_amount"] as const;
const feeNames = ["平台佣金", "活动额外佣金", "达人佣金", "物流成本", "关税", "支付手续费", "汇率损耗", "其他可变费用", "卖家优惠券"];

function csvHeaders(text: string): string[] {
  const header = text.split(/\r?\n/, 1)[0] ?? ""; const cells: string[] = []; let value = ""; let quoted = false;
  for (let i = 0; i < header.length; i++) { const char = header[i]; if (char === '"') { if (quoted && header[i + 1] === '"') { value += '"'; i++; } else quoted = !quoted; } else if (char === "," && !quoted) { cells.push(value); value = ""; } else value += char; }
  cells.push(value); return cells.map((cell) => cell.replace(/^\uFEFF/, "").trim());
}

export default function ReconciliationPage() {
  const { locale } = useAuth(); const zh = locale === "zh"; const t = (cn: string, en: string) => zh ? cn : (translations as Record<string, string>)[cn] ?? en;
  const [forecasts, setForecasts] = useState<Awaited<ReturnType<typeof api.forecasts>>>([]);
  const [snapshotId, setSnapshotId] = useState(0); const [file, setFile] = useState<File | null>(null); const [headers, setHeaders] = useState<string[]>([]);
  const [dateFormat, setDateFormat] = useState(""); const [fieldMap, setFieldMap] = useState<Record<string, string>>({}); const [feeMap, setFeeMap] = useState<Record<string, string>>({}); const [feeSigns, setFeeSigns] = useState<Record<string, number>>({});
  const [preview, setPreview] = useState<Awaited<ReturnType<typeof api.settlementUpload>> | null>(null);
  const [report, setReport] = useState<Awaited<ReturnType<typeof api.runReconciliation>> | null>(null);
  const [error, setError] = useState(""); const [busy, setBusy] = useState(false);
  useEffect(() => { void api.forecasts().then((items) => { setForecasts(items); if (items[0]) setSnapshotId(items[0].id); }).catch((reason) => setError(String(reason))); }, []);
  const selected = forecasts.find((item) => item.id === snapshotId);
  const chooseFile = async (next: File | null) => { setFile(next); setPreview(null); setReport(null); setFieldMap({}); setFeeMap({}); setFeeSigns({}); setDateFormat(""); if (!next) return; try { const bytes = await next.arrayBuffer(); let decoded: string; try { decoded = new TextDecoder("utf-8", { fatal: true }).decode(bytes); } catch { decoded = new TextDecoder("gbk").decode(bytes); } setHeaders(csvHeaders(decoded)); } catch (reason) { setError(String(reason)); } };
  const columnMapping = { fields: fieldMap, fee_columns: Object.fromEntries(Object.keys(feeMap).filter((column) => feeMap[column] && feeMap[column] !== "__NON_FEE__").map((column) => [column, column])), ignored_columns: Object.keys(feeMap).filter((column) => feeMap[column] === "__NON_FEE__"), fee_signs: feeSigns, date_format: dateFormat || undefined };
  const perform = async (action: "import" | "confirm") => { if (!file || !selected) return; setBusy(true); setError(""); try { const uploaded = await api.settlementUpload(action, file, selected.platform, columnMapping, mappedFees); if (action === "import") { setPreview(uploaded); return; } if (!uploaded.import_id) throw new Error("Missing import ID"); setReport(await api.runReconciliation(snapshotId, uploaded.import_id)); setPreview(null); } catch (reason) { setError(reason instanceof Error ? reason.message : String(reason)); } finally { setBusy(false); } };
  const used = new Set(Object.values(fieldMap));
  const mappedFees = Object.fromEntries(Object.entries(feeMap).filter(([, value]) => value !== "__NON_FEE__").map(([column, value]) => [column, value === "__UNMAPPED__" ? column : value]));
  return <div className="space-y-6">
    <div><h2 className="text-xl font-semibold">{t("精度验证", "Accuracy validation")}</h2><p className="mt-2 text-sm text-slate-600">{t("可选：上传结算单校准本店铺的预测区间。选择归档预测并确认列映射后，核对费用与预测偏差。", "Optional: upload a settlement CSV to calibrate your shop forecast range. Select a frozen forecast, confirm the column mapping, and review the differences.")}</p></div>
    {error && <p role="alert" className="rounded-lg bg-red-50 p-3 text-sm text-red-700">{error}</p>}
    <Card><CardHeader><CardTitle>1. {t("选择归档分析", "Select a forecast")}</CardTitle></CardHeader><CardContent><select className="h-10 w-full rounded-md border bg-white px-3" value={snapshotId} onChange={(event) => { setSnapshotId(Number(event.target.value)); setPreview(null); setReport(null); }}>{forecasts.map((item) => <option value={item.id} key={item.id}>{item.activity_name} · {item.sku} · {item.platform} · {item.frozen_at.slice(0, 10)}</option>)}</select>{forecasts.length === 0 && <p className="mt-2 text-sm text-amber-700">{t("请先归档一次活动分析。", "Archive an analysis first.")}</p>}</CardContent></Card>
    <Card><CardHeader><CardTitle>2. {t("上传并映射结算单", "Upload and map CSV")}</CardTitle></CardHeader><CardContent className="space-y-4"><Input type="file" accept=".csv,text/csv" onChange={(event) => void chooseFile(event.target.files?.[0] ?? null)} />{headers.length > 0 && <><p className="text-xs text-slate-500">{t("请选择 CSV 中实际对应的列。平台导出列名因站点而异，系统不预设真实列名。", "Select the actual CSV columns. Export headers vary by site; no real platform column names are assumed.")}</p><div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-3">{fields.map((field) => <label className="space-y-1 text-sm" key={field}><span>{field}{fields.indexOf(field) < 5 ? " *" : ""}</span><select className="h-10 w-full rounded-md border bg-white px-3" value={fieldMap[field] ?? ""} onChange={(event) => { setFieldMap({ ...fieldMap, [field]: event.target.value }); setPreview(null); }}><option value="">{t("未选择", "Unselected")}</option>{headers.map((column) => <option key={column} value={column}>{column}</option>)}</select></label>)}</div><label className="block space-y-1 text-sm"><span>{t("日期格式（默认 ISO）", "Date format (ISO by default)")}</span><Input value={dateFormat} onChange={(event) => { setDateFormat(event.target.value); setPreview(null); }} placeholder="%Y/%m/%d" /></label><div><h3 className="mb-2 text-sm font-medium">{t("费项列与口径", "Fee columns and categories")}</h3><div className="grid gap-2 sm:grid-cols-2">{headers.filter((column) => !used.has(column)).map((column) => <label key={column} className="flex items-center justify-between gap-3 text-sm"><span className="truncate" title={column}>{column}</span><select className="h-9 max-w-44 rounded-md border bg-white px-2" value={feeMap[column] ?? ""} onChange={(event) => { setFeeMap({ ...feeMap, [column]: event.target.value }); setPreview(null); }}><option value="">{t("未识别列", "Unrecognized column")}</option><option value="__NON_FEE__">{t("确认非费项", "Confirmed non-fee")}</option><option value="__UNMAPPED__">{t("未映射费项", "Unmapped fee")}</option>{feeNames.map((name) => <option key={name} value={name}>{name}</option>)}</select>{feeMap[column] && feeMap[column] !== "__NON_FEE__" && <select className="h-9 rounded-md border bg-white px-2" value={feeSigns[column] ?? 1} onChange={(event) => { setFeeSigns({ ...feeSigns, [column]: Number(event.target.value) }); setPreview(null); }}><option value={1}>{t("费用为正", "Positive charge")}</option><option value={-1}>{t("费用为负", "Negative charge")}</option></select>}</label>)}</div></div><Button disabled={busy || !file || !fields.slice(0, 5).every((field) => fieldMap[field])} onClick={() => void perform("import")}>{t("解析预览", "Preview CSV")}</Button></>}</CardContent></Card>
    {preview && <Card><CardHeader><CardTitle>3. {t("确认导入", "Confirm import")}</CardTitle></CardHeader><CardContent className="space-y-3 text-sm"><p>{t("解析行数", "Rows")}: {preview.row_count}</p><p>{t("未识别列", "Unrecognized columns")}: {preview.unrecognized_columns.join("、") || "—"}</p><p>{t("未映射费项", "Unmapped fees")}: {preview.unmapped_fees?.length ?? 0}</p>{(preview.unmapped_fees?.length ?? 0) > 0 && <p className="text-amber-700">{preview.unmapped_fees?.slice(0, 5).map((item) => `${item.fee_name}: ${item.amount}`).join(" · ")}</p>}<div className="overflow-x-auto"><pre className="max-h-40 overflow-auto rounded bg-slate-50 p-3 text-xs">{JSON.stringify(preview.preview, null, 2)}</pre></div><Button disabled={busy} onClick={() => void perform("confirm")}>{t("确认并运行对账", "Confirm and reconcile")}</Button></CardContent></Card>}
    {report && <Card><CardHeader><CardTitle>4. {t("对账报告", "Reconciliation report")}</CardTitle></CardHeader><CardContent className="space-y-4"><p className="text-sm">{t("公式正确性", "Formula verdict")}: <strong>{report.formula_verdict}</strong> · {t("最大费项差额", "Maximum fee difference")}: {report.max_fee_diff}</p><p className="text-sm">{t("预测有效性", "Forecast accuracy")}: {t("预计销量", "Forecast sales")} {report.forecast_diff.estimated_sales} / {t("实际销量", "Actual sales")} {report.forecast_diff.actual_sales} · {t("预计退货率", "Forecast return rate")} {report.forecast_diff.predicted_return_rate} / {t("实际退货率", "Actual return rate")} {report.forecast_diff.actual_return_rate ?? "—"} · {t("实际退货件数", "Returned units")} {report.forecast_diff.returned_units}</p><div className="overflow-x-auto"><table className="w-full text-left text-sm"><thead><tr className="border-b">{["Order", "Fee", "Forecast", "Actual", "Diff", "Reason"].map((name) => <th className="p-2" key={name}>{name}</th>)}</tr></thead><tbody>{report.diff_data.fee_diffs.map((row, index) => <tr key={index} className={row.formula_pass ? "border-b" : "border-b bg-red-50 text-red-800"}><td className="p-2">{row.order_id}</td><td className="p-2">{row.fee_item}</td><td className="p-2">{row.predicted}</td><td className="p-2">{row.actual}</td><td className="p-2">{row.absolute_diff}</td><td className="p-2">{row.reason}</td></tr>)}</tbody></table></div><p className="text-sm text-amber-700">{t("未映射费项", "Unmapped fees")}: {report.diff_data.unmapped_fees.length} · {t("无法关联订单", "Unmatched orders")}: {report.diff_data.unmatched_orders.length} · {t("未核对费项", "Unverified fees")}: {report.diff_data.unverified_fees.length}</p><Button asChild variant="outline"><a href={api.reconciliationExportUrl(report.id)}>{t("导出 XLSX", "Export XLSX")}</a></Button></CardContent></Card>}
  </div>;
}
