"use client";

import { useEffect, useMemo, useState } from "react";
import { api } from "@/lib/api";
import translations from "@/lib/auto-translations.json";
import { useAuth } from "@/components/auth-provider";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import type { BootstrapData, PromotionActivity } from "@/types";

const initialActivity: PromotionActivity = { platform: "tiktok_shop", activity_name: "Portfolio", activity_type: "promotion", source_url: null, start_date: null, end_date: null, discount_type: "none", discount_value: "0", minimum_discount: null, platform_commission_rate: null, extra_commission_rate: "0", creator_commission_rate: null, shipping_subsidy: "0", seller_shipping_cost: null, platform_subsidy: "0", coupon_cost_bearer: "seller", coupon_amount: "0", minimum_price_requirement: null, minimum_stock_requirement: null, estimated_traffic_lift: null, estimated_sales: 0, return_rate_override: null, currency: "USD", notes: "", raw_text: "", parse_confidence: "0", missing_fields: [], registration_fee: "0", ad_budget: "0", creative_cost: "0", creator_fixed_fee: "0" };

export default function PortfolioPage() {
  const { locale } = useAuth(); const zh = locale === "zh"; const t = (cn: string, en: string) => zh ? cn : (translations as Record<string, string>)[cn] ?? en;
  const [data, setData] = useState<BootstrapData | null>(null); const [activity, setActivity] = useState<PromotionActivity>(initialActivity);
  const [chosen, setChosen] = useState<Record<number, number>>({}); const [report, setReport] = useState<Awaited<ReturnType<typeof api.portfolio>> | null>(null);
  const [error, setError] = useState(""); const [busy, setBusy] = useState(false);
  useEffect(() => { void api.bootstrap().then(setData).catch((reason) => setError(String(reason))); }, []);
  const eligible = useMemo(() => data?.products.filter((product) => product.currency === activity.currency && product.platform_configs.some((config) => config.platform === activity.platform)) ?? [], [data, activity]);
  const update = (key: keyof PromotionActivity, value: string) => { setActivity({ ...activity, [key]: value }); setReport(null); };
  const run = async () => { setBusy(true); setError(""); try { const items = eligible.filter((product) => chosen[product.id] !== undefined).map((product) => ({ product_id: product.id, platform_config: product.platform_configs.find((config) => config.platform === activity.platform)!, estimated_sales: chosen[product.id] })); setReport(await api.portfolio({ activity, items })); } catch (reason) { setError(reason instanceof Error ? reason.message : String(reason)); } finally { setBusy(false); } };
  return <div className="space-y-6"><div><h2 className="text-xl font-semibold">{t("多 SKU 组合分析", "Multi SKU portfolio")}</h2><p className="mt-2 text-sm text-slate-600">{t("同一场活动选择多个商品，固定报名与投放成本只扣一次。", "Select multiple SKUs for one campaign. Fixed campaign costs are deducted once.")}</p></div>{error && <p role="alert" className="rounded bg-red-50 p-3 text-sm text-red-700">{error}</p>}
    <Card><CardHeader><CardTitle>{t("活动与固定投入", "Campaign and fixed costs")}</CardTitle></CardHeader><CardContent className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4"><label className="space-y-1 text-sm"><span>{t("平台", "Platform")}</span><select className="h-10 w-full rounded-md border bg-white px-3" value={activity.platform} onChange={(event) => update("platform", event.target.value)}><option value="tiktok_shop">TikTok Shop</option><option value="amazon">Amazon</option></select></label><label className="space-y-1 text-sm"><span>{t("活动名称", "Campaign name")}</span><Input value={activity.activity_name} onChange={(event) => update("activity_name", event.target.value)} /></label><label className="space-y-1 text-sm"><span>{t("币种", "Currency")}</span><Input value={activity.currency} onChange={(event) => update("currency", event.target.value.toUpperCase())} /></label><label className="space-y-1 text-sm"><span>{t("折扣比例，例如 0.2", "Discount rate, e.g. 0.2")}</span><Input value={activity.discount_value} onChange={(event) => { setActivity({ ...activity, discount_type: "percentage", discount_value: event.target.value }); setReport(null); }} /></label>{(["registration_fee", "ad_budget", "creative_cost", "creator_fixed_fee"] as const).map((key) => <label key={key} className="space-y-1 text-sm"><span>{key}</span><Input type="number" min="0" value={activity[key]} onChange={(event) => update(key, event.target.value)} /></label>)}</CardContent></Card>
    <Card><CardHeader><CardTitle>{t("选择商品及预计销量", "Select SKUs and expected sales")}</CardTitle></CardHeader><CardContent className="space-y-3">{eligible.map((product) => <label key={product.id} className="flex items-center gap-4 rounded-lg border p-3 text-sm"><input type="checkbox" checked={chosen[product.id] !== undefined} onChange={(event) => { const next = { ...chosen }; if (event.target.checked) next[product.id] = 100; else delete next[product.id]; setChosen(next); setReport(null); }} /><span className="min-w-0 flex-1">{product.name} · {product.sku}</span><Input className="w-28" type="number" min="0" disabled={chosen[product.id] === undefined} value={chosen[product.id] ?? ""} onChange={(event) => { setChosen({ ...chosen, [product.id]: Number(event.target.value) }); setReport(null); }} /></label>)}{eligible.length === 0 && <p className="text-sm text-slate-500">{t("当前平台和币种没有可分析商品。", "No products match this platform and currency.")}</p>}<Button disabled={busy || !eligible.some((product) => chosen[product.id] !== undefined)} onClick={() => void run()}>{t("计算组合", "Analyze portfolio")}</Button></CardContent></Card>
    {report && <Card><CardHeader><CardTitle>{t("组合结果", "Portfolio result")}</CardTitle></CardHeader><CardContent className="space-y-4 text-sm"><div className="grid gap-3 sm:grid-cols-3"><p>{t("总利润", "Total profit")}: <strong>{report.total_profit}</strong></p><p>{t("加权利润率", "Weighted margin")}: <strong>{report.weighted_margin}</strong></p><p>{t("固定成本", "Fixed cost")}: <strong>{report.fixed_cost}</strong></p></div><p>{t("风险分布", "Risk distribution")}: {Object.entries(report.risk_distribution).map(([key, count]) => `${key}: ${count}`).join(" · ")}</p><div className="space-y-2">{report.sku_results.map((row) => <div className="flex justify-between border-b py-2" key={row.sku}><span>{row.sku} · {row.risk_level}</span><span>{row.marginal_contribution} / {row.margin}</span></div>)}</div><h3 className="font-semibold">{t("建议复核的 SKU（按边际贡献排序）", "SKUs to review (by marginal contribution)")}</h3>{report.exclude_candidates.map((row) => <p className="text-amber-700" key={row.sku}>{row.sku} · {row.marginal_contribution} · {row.reason === "NEGATIVE_CONTRIBUTION" ? t("边际利润非正", "Nonpositive contribution") : t("拉低组合利润率", "Dilutes portfolio margin")}</p>)}{report.exclude_candidates.length === 0 && <p>—</p>}</CardContent></Card>}
  </div>;
}
