"use client";

import { useEffect, useState } from "react";
import { KeyRound, Plus, Trash2 } from "lucide-react";
import { api } from "@/lib/api";
import { useAuth } from "@/components/auth-provider";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import type { HistoricalRow, PlatformConnection } from "@/types";

const initial = { platform: "tiktok_shop", label: "", shop_id: "", app_key: "", app_secret: "", access_token: "" };
const historicalInitial = { platform: "tiktok_shop", period: "", visitors: "", orders: "", returns: "", source: "" };

export default function ConnectionsPage() {
  const { locale } = useAuth(); const zh = locale === "zh";
  const [catalog, setCatalog] = useState<Array<{ id: string; name: string; region: string }>>([]);
  const [rows, setRows] = useState<PlatformConnection[]>([]);
  const [metrics, setMetrics] = useState<HistoricalRow[]>([]);
  const [form, setForm] = useState(initial); const [historical, setHistorical] = useState(historicalInitial);
  const [busy, setBusy] = useState(false); const [error, setError] = useState(""); const [success, setSuccess] = useState("");
  const refresh = async () => { const [platforms, connections, history] = await Promise.all([api.platformCatalog(), api.connections(), api.historicalMetrics()]); setCatalog(platforms); setRows(connections); setMetrics(history); };
  useEffect(() => { void refresh().catch((reason) => setError(reason instanceof Error ? reason.message : "Failed to load")); }, []);
  const save = async (event: React.FormEvent) => { event.preventDefault(); setBusy(true); setError(""); setSuccess(""); try { await api.createConnection(form); setForm(initial); await refresh(); setSuccess(zh ? "凭据已加密保存。平台授权和数据同步仍需完成。" : "Credentials saved securely. Platform authorization and sync are still pending."); } catch (reason) { setError(reason instanceof Error ? reason.message : "Failed to save"); } finally { setBusy(false); } };
  const remove = async (id: number) => { if (!window.confirm(zh ? "删除这条平台连接？" : "Delete this platform connection?")) return; try { await api.deleteConnection(id); await refresh(); } catch (reason) { setError(reason instanceof Error ? reason.message : "Failed to delete"); } };
  const addMetric = async (event: React.FormEvent) => { event.preventDefault(); setBusy(true); setError(""); try { await api.addHistoricalMetric({ platform: historical.platform, period: historical.period, visitors: historical.visitors === "" ? null : Number(historical.visitors), orders: historical.orders === "" ? null : Number(historical.orders), returns: historical.returns === "" ? null : Number(historical.returns), source: historical.source }); setHistorical(historicalInitial); await refresh(); } catch (reason) { setError(reason instanceof Error ? reason.message : "Failed to save"); } finally { setBusy(false); } };
  return <div className="space-y-7">
    <div><h2 className="text-xl font-semibold">{zh ? "平台连接" : "Platform connections"}</h2><p className="mt-2 text-sm text-slate-600">{zh ? "一个商家账号可保存多家店铺、多个平台的 API 凭据。凭据仅保存在服务端，页面不会再次显示。" : "Keep multiple shops and platform API credentials under one merchant account. Secrets stay on the server and are never displayed again."}</p></div>
    {error && <p role="alert" className="rounded-lg bg-red-50 p-3 text-sm text-red-700">{error}</p>}{success && <p role="status" className="rounded-lg bg-emerald-50 p-3 text-sm text-emerald-700">{success}</p>}
    <div className="grid gap-6 xl:grid-cols-[1fr_1.1fr]">
      <Card><CardHeader><CardTitle className="flex items-center gap-2"><Plus className="size-5" />{zh ? "添加平台 API" : "Add platform API"}</CardTitle><CardDescription>{zh ? "保存密钥后仍需对应平台审核或 OAuth 授权；状态不会冒充已同步。" : "Saving keys does not grant platform permissions or start data sync."}</CardDescription></CardHeader><CardContent><form onSubmit={(event) => void save(event)} className="grid gap-4 sm:grid-cols-2"><label className="space-y-2 text-sm"><span>{zh ? "平台" : "Platform"}</span><select className="h-10 w-full rounded-md border bg-white px-3" value={form.platform} onChange={(event) => setForm({ ...form, platform: event.target.value })}>{catalog.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select></label><label className="space-y-2 text-sm"><span>{zh ? "连接名称" : "Connection name"}</span><Input required value={form.label} onChange={(event) => setForm({ ...form, label: event.target.value })} placeholder={zh ? "如：TikTok 美国店" : "e.g. US shop"} /></label><label className="space-y-2 text-sm"><span>{zh ? "店铺 ID（可选）" : "Shop ID (optional)"}</span><Input value={form.shop_id} onChange={(event) => setForm({ ...form, shop_id: event.target.value })} /></label><label className="space-y-2 text-sm"><span>App Key</span><Input value={form.app_key} onChange={(event) => setForm({ ...form, app_key: event.target.value })} autoComplete="off" /></label><label className="space-y-2 text-sm"><span>App Secret</span><Input type="password" value={form.app_secret} onChange={(event) => setForm({ ...form, app_secret: event.target.value })} autoComplete="off" /></label><label className="space-y-2 text-sm"><span>Access Token</span><Input type="password" value={form.access_token} onChange={(event) => setForm({ ...form, access_token: event.target.value })} autoComplete="off" /></label><Button className="sm:col-span-2" disabled={busy || !form.label}>{busy ? (zh ? "保存中" : "Saving") : (zh ? "保存平台连接" : "Save connection")}</Button></form></CardContent></Card>
      <Card><CardHeader><CardTitle>{zh ? "我的平台" : "My platforms"}</CardTitle><CardDescription>{zh ? "同一平台可按不同店铺分别添加。" : "Add separate connections for multiple shops on the same platform."}</CardDescription></CardHeader><CardContent className="space-y-3">{rows.length === 0 ? <p className="text-sm text-slate-500">{zh ? "尚未添加平台连接" : "No platform connections yet"}</p> : rows.map((row) => <div key={row.id} className="flex items-start justify-between gap-4 rounded-xl border bg-white p-4"><div><p className="font-medium">{row.label}</p><p className="mt-1 text-sm text-slate-500">{catalog.find((item) => item.id === row.platform)?.name ?? row.platform}{row.shop_id ? ` · ${row.shop_id}` : ""}</p><p className="mt-2 text-xs text-amber-700">{row.status === "deprecated" ? (zh ? "旧平台连接已下架，历史凭据仍保留" : "Legacy connection deprecated; saved credentials retained") : row.status === "awaiting_credentials" ? (zh ? "尚未填写凭据" : "Credentials missing") : (zh ? "凭据已保存 · 尚未验证平台授权或同步数据" : "Credentials saved · authorization and data sync unverified")}</p><p className="mt-1 flex items-center gap-1 text-xs text-slate-400"><KeyRound className="size-3" />{row.has_app_key ? "App Key · " : ""}{row.has_app_secret ? "App Secret · " : ""}{row.has_access_token ? "Token" : ""}</p></div><button type="button" onClick={() => void remove(row.id)} aria-label={zh ? "删除" : "Delete"} className="rounded-md p-2 text-slate-400 hover:bg-red-50 hover:text-red-600"><Trash2 className="size-4" /></button></div>)}</CardContent></Card>
    </div>
    <Card><CardHeader><CardTitle>{zh ? "店铺历史指标" : "Shop history"}</CardTitle><CardDescription>{zh ? "公开网页无法取得你的往年访客、订单和退货。平台授权同步尚未完成时，可录入同一时段、同一口径的后台数据；分析会自动读取这里的最新记录。" : "Public pages cannot reveal your past shop visitors, orders or returns. Until authorized sync is available, you can enter export totals from the same period and reporting basis. Analysis uses the latest record automatically."}</CardDescription></CardHeader><CardContent><form onSubmit={(event) => void addMetric(event)} className="grid gap-3 sm:grid-cols-2 lg:grid-cols-6">{[[zh ? "平台" : "Platform", "platform"], [zh ? "时段" : "Period", "period"], [zh ? "访客" : "Visitors", "visitors"], [zh ? "订单" : "Orders", "orders"], [zh ? "退货" : "Returns", "returns"], [zh ? "数据来源" : "Source", "source"]].map(([label, key]) => <label key={key} className="space-y-2 text-sm"><span>{label}</span>{key === "platform" ? <select className="h-10 w-full rounded-md border bg-white px-3" value={historical.platform} onChange={(event) => setHistorical({ ...historical, platform: event.target.value })}>{catalog.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select> : <Input type={["visitors", "orders", "returns"].includes(key) ? "number" : "text"} min={0} required={["period", "source"].includes(key)} value={historical[key as keyof typeof historical]} onChange={(event) => setHistorical({ ...historical, [key]: event.target.value })} />}</label>)}<Button disabled={busy} className="lg:col-span-6">{zh ? "保存历史指标" : "Save historical metrics"}</Button></form><div className="mt-5 space-y-2">{metrics.slice(0, 5).map((row) => <div key={row.id} className="rounded-lg border px-4 py-3 text-sm"><strong>{row.platform}</strong> · {row.period} · {zh ? "访客" : "visitors"} {row.visitors ?? "—"} · {zh ? "订单" : "orders"} {row.orders ?? "—"} · {zh ? "退货" : "returns"} {row.returns ?? "—"}<span className="ml-2 text-slate-500">{row.source}</span></div>)}</div></CardContent></Card>
  </div>;
}
