"use client";

import { Suspense, useEffect, useMemo, useRef, useState } from "react";
import { useSearchParams } from "next/navigation";
import Link from "next/link";
import { Archive, AlertTriangle, ArrowLeft, ArrowRight, BadgeDollarSign, Check, CheckCircle2, LayoutDashboard, Package, ScanSearch, Sparkles, TrendingUp, Truck, Users } from "lucide-react";
import { useData } from "@/components/data-provider";
import { useAuth } from "@/components/auth-provider";
import { ErrorState, PageSkeleton, RiskBadge } from "@/components/common";
import { Alert, AlertDescription, AlertTitle } from "@/components/ui/alert";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Progress } from "@/components/ui/progress";
import { Separator } from "@/components/ui/separator";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import { Textarea } from "@/components/ui/textarea";
import { api } from "@/lib/api";
import { cn, money, percent, platformName, quantity } from "@/lib/utils";
import type { AnalysisRun, DemoCase, ParsedPromotion, Product, ProfitAnalysisRequest, PromotionActivity } from "@/types";

const steps = ["选择商品", "活动规则", "参数确认", "盈利分析"];

function Stepper({ current }: { current: number }) {
  return <div className="overflow-x-auto"><div className="flex min-w-[560px] items-center rounded-xl border bg-white p-3">{steps.map((label, i) => <div key={label} className="flex flex-1 items-center last:flex-none"><div className="flex items-center gap-2"><span className={cn("grid size-7 place-items-center rounded-full border text-xs font-semibold", i + 1 < current && "border-slate-900 bg-slate-900 text-white", i + 1 === current && "border-blue-600 bg-blue-50 text-blue-700", i + 1 > current && "bg-white text-slate-400")}>{i + 1 < current ? <Check className="size-3.5" /> : i + 1}</span><span className={cn("text-sm", i + 1 === current ? "font-medium text-slate-950" : "text-slate-500")}>{label}</span></div>{i < steps.length - 1 && <div className="mx-4 h-px flex-1 bg-slate-200" />}</div>)}</div></div>;
}

function ProductCard({ product, selected, onClick }: { product: Product; selected: boolean; onClick: () => void }) {
  return <button onClick={onClick} className={cn("w-full rounded-xl border bg-white p-5 text-left shadow-sm hover:border-slate-300", selected && "border-blue-500 ring-2 ring-blue-100")}><div className="flex items-start justify-between"><div className="grid size-10 place-items-center rounded-lg bg-slate-100 text-slate-600"><Package className="size-5" /></div>{selected && <span className="grid size-6 place-items-center rounded-full bg-blue-600 text-white"><Check className="size-3.5" /></span>}</div><h3 className="mt-5 font-semibold">{product.name}</h3><p className="mt-1 text-xs text-slate-500">{product.sku}</p><div className="mt-5 grid grid-cols-2 gap-3 border-t pt-4 text-sm"><div><p className="text-xs text-slate-500">采购成本</p><p className="mt-1 font-medium tabular">{money(product.purchase_cost,product.currency)}</p></div><div><p className="text-xs text-slate-500">已配置平台</p><p className="mt-1 font-medium">{product.platform_configs.length} 个</p></div></div><div className="mt-4 flex flex-wrap gap-2">{product.platform_configs.map((x) => <Badge key={x.platform} variant="outline">{platformName(x.platform)}</Badge>)}</div></button>;
}

function Waterfall({ result, currency }: { result: AnalysisRun["result"]; currency: string }) {
  const items = result.breakdown.filter((x) => Number(x.amount) !== 0);
  const values = [{ item: "活动售价", amount: Number(result.selling_price), type: "start" }, ...items.map((x) => ({ item: x.item, amount: Number(x.amount), type: Number(x.amount) < 0 ? "gain" : "cost" })), { item: "真实利润", amount: Number(result.unit_profit), type: "total" }];
  const cumulative: number[] = [Number(result.selling_price)];
  items.forEach((x) => cumulative.push(cumulative[cumulative.length - 1] - Number(x.amount)));
  const min = Math.min(0, ...cumulative, Number(result.unit_profit)); const max = Math.max(...cumulative, Number(result.selling_price));
  const width = Math.max(900, values.length * 82), height = 330, top = 24, bottom = 78, chartH = height - top - bottom;
  const y = (v: number) => top + ((max - v) / Math.max(max - min, .01)) * chartH;
  return <div className="scrollbar-subtle overflow-x-auto"><svg viewBox={`0 0 ${width} ${height}`} className="min-w-[900px]" role="img" aria-label="利润成本瀑布图"><line x1="30" x2={width - 20} y1={y(0)} y2={y(0)} stroke="#cbd5e1" strokeDasharray="4 4" />{values.map((item, i) => { const x = 34 + i * ((width - 68) / values.length); const w = 44; let from = 0, to = item.amount; if (item.type === "cost" || item.type === "gain") { from = cumulative[i - 1]; to = cumulative[i]; } const yy = y(Math.max(from, to)); const h = Math.max(3, Math.abs(y(from) - y(to))); const color = item.type === "cost" ? "#e11d48" : item.type === "gain" ? "#16a34a" : item.type === "total" ? "#2563eb" : "#0f172a"; return <g key={`${item.item}-${i}`}>{i > 0 && i < values.length - 1 && <line x1={x - 16} x2={x} y1={y(from)} y2={y(from)} stroke="#94a3b8" strokeDasharray="3 3" />}<rect x={x} y={yy} width={w} height={h} rx="3" fill={color} opacity=".9"/><text x={x + w/2} y={Math.max(14, yy - 7)} textAnchor="middle" fontSize="10" fill="#475569">{money(item.type === "cost" ? -item.amount : item.amount, currency)}</text><text transform={`translate(${x + w/2},${height - 58}) rotate(-38)`} textAnchor="end" fontSize="10" fill="#64748b">{item.item}</text></g>; })}</svg></div>;
}

function AnalysisResultView({ run, request, rerun, archive, archiving, archiveError }: { run: AnalysisRun; request: ProfitAnalysisRequest; rerun: (request: ProfitAnalysisRequest) => Promise<void>; archive: () => Promise<void>; archiving: boolean; archiveError: string | null }) {
  const { locale } = useAuth(); const zh = locale === "zh";
  const [simulating, setSimulating] = useState(false); const result = run.result; const displayMoney = (value: string | number | null | undefined) => money(value, request.activity.currency);
  const scenarioNameEn: Record<string, string> = { "基准": "Baseline", "乐观": "Optimistic", "悲观": "Pessimistic", "物流+10%": "Shipping +10%", "物流-10%": "Shipping -10%", "退货率+20%": "Return rate +20%", "退货率-20%": "Return rate -20%" };
  const simulate = async (kind: "shipping" | "creator" | "price") => { const next = structuredClone(request); if (kind === "shipping") next.activity.seller_shipping_cost = String(Number(next.activity.seller_shipping_cost ?? next.platform_config.shipping_cost) * .9); if (kind === "creator") next.activity.creator_commission_rate = String(Math.max(0, Number(next.activity.creator_commission_rate ?? 0) - .03)); if (kind === "price" && result.break_even_price) { next.activity.discount_type = "fixed_price"; next.activity.discount_value = String(Number(result.break_even_price) + .5); } setSimulating(true); await rerun(next); setSimulating(false); };
  const downloadCsv = () => { const rows = [["项目","金额","公式"], ...result.breakdown.map((x) => [x.item,x.amount,x.formula])]; const csv = rows.map((row) => row.map((x) => `"${String(x).replaceAll('"','""')}"`).join(",")).join("\n"); const link = document.createElement("a"); link.href=URL.createObjectURL(new Blob(["\ufeff"+csv],{type:"text/csv"})); link.download=`${request.activity.activity_name}.csv`; link.click(); };
  return <div className="space-y-6"><Card className="overflow-hidden border-slate-200 shadow-sm"><div className="h-1 bg-slate-900"/><CardContent className="p-6 sm:p-8"><div className="flex flex-col justify-between gap-6 lg:flex-row"><div><div className="flex flex-wrap items-center gap-3"><RiskBadge level={result.risk_level} label={result.risk_label}/><Badge variant="outline">{platformName(request.activity.platform)}</Badge></div><h2 className="mt-5 text-2xl font-semibold tracking-tight">{request.activity.activity_name}</h2><p className="mt-1 text-sm text-slate-500">{request.product.name} · {request.product.sku}</p></div><div className="grid grid-cols-2 gap-x-10 gap-y-5 sm:grid-cols-4"><div><p className="text-xs text-slate-500">单件预估利润</p><p className={cn("mt-2 text-3xl font-semibold tabular", Number(result.unit_profit) < 0 ? "text-red-600" : "text-slate-950")}>{displayMoney(result.unit_profit)}</p></div><div><p className="text-xs text-slate-500">利润率</p><p className="mt-2 text-2xl font-semibold tabular">{percent(result.profit_margin)}</p></div><div><p className="text-xs text-slate-500">预计总利润</p><p className={cn("mt-2 text-2xl font-semibold tabular", Number(result.estimated_total_profit) < 0 ? "text-red-600" : "text-emerald-700")}>{displayMoney(result.estimated_total_profit)}</p></div><div><p className="text-xs text-slate-500">最低安全活动价</p><p className="mt-2 text-2xl font-semibold tabular">{displayMoney(result.break_even_price)}</p></div></div></div><Separator className="my-6"/><div className="flex flex-wrap items-center justify-between gap-3"><p className="text-sm text-slate-600">建议活动价至少提高至 <strong className="text-slate-950">{displayMoney(result.break_even_price)}</strong>{result.break_even_quantity ? `，售出 ${result.break_even_quantity} 件可覆盖固定投入。` : "。当前以可变成本为主。"}</p><div className="flex gap-2"><Button variant="outline" size="sm" onClick={downloadCsv}>导出 CSV</Button>{run.analysis_id && <Button asChild variant="outline" size="sm"><a href={api.exportUrl(run.analysis_id,"xlsx")}>导出 Excel</a></Button>}</div></div>
      <div className={cn("mt-6 flex flex-col gap-4 rounded-xl border p-4 sm:flex-row sm:items-center sm:justify-between", run.analysis_id ? "border-emerald-400/70 bg-emerald-50/40" : "border-slate-500/60 bg-transparent")}>
        <div className="flex gap-3">{run.analysis_id ? <CheckCircle2 className="mt-0.5 size-5 shrink-0 text-emerald-700"/> : <Archive className="mt-0.5 size-5 shrink-0 text-slate-700"/>}<div><p className="text-sm font-semibold">{run.analysis_id ? "已归档并同步到 Dashboard" : "当前是分析预览，尚未计入 Dashboard"}</p><p className="mt-1 text-xs leading-5 text-slate-500">{run.analysis_id ? "首页指标、活动趋势、历史记录和报告导出均已更新。" : "确认结果后归档；你也可以先调整参数或模拟方案，不会污染首页数据。"}</p>{run.revision_message&&<p className="mt-2 text-xs text-emerald-700">{run.revision_message}</p>}{archiveError&&<p className="mt-2 text-xs text-red-600">{archiveError}</p>}</div></div>
        <div className="flex shrink-0 flex-wrap gap-2">{run.analysis_id ? <><Button asChild size="sm"><Link href="/"><LayoutDashboard className="size-4"/>查看 Dashboard</Link></Button><Button asChild variant="outline" size="sm"><Link href={`/history/${run.analysis_id}`}>查看归档</Link></Button></> : <Button size="sm" disabled={archiving} onClick={()=>void archive()}><Archive className="size-4"/>{archiving?"正在归档":"归档到 Dashboard"}</Button>}</div>
      </div>
    </CardContent></Card>
    {Number(result.unit_profit) < 0 && <Alert variant="destructive" className="bg-red-50"><AlertTriangle className="size-4"/><AlertTitle>销量增加不能解决负单件利润</AlertTitle><AlertDescription>当前每多卖一件都会扩大活动亏损，应先调整售价或佣金结构。</AlertDescription></Alert>}
    <div className="grid gap-6 xl:grid-cols-3"><Card className="xl:col-span-2"><CardHeader><CardTitle>利润是怎么被吃掉的？</CardTitle><CardDescription>从活动成交价开始，逐项扣除已填成本</CardDescription></CardHeader><CardContent><Waterfall result={result} currency={request.activity.currency}/></CardContent></Card><Card><CardHeader><CardTitle>费用拆解</CardTitle><CardDescription>按单件活动售价计算</CardDescription></CardHeader><CardContent className="space-y-3">{result.breakdown.filter((x)=>Number(x.amount)!==0).map((x)=><div key={x.item} className="flex items-center justify-between border-b pb-3 text-sm last:border-0"><div><p className="text-slate-700">{x.item}</p><p className="mt-0.5 text-xs text-slate-400">{Math.abs(Number(x.amount)/Number(result.selling_price)*100).toFixed(1)}%</p></div><span className={cn("font-medium tabular",Number(x.amount)<0?"text-emerald-600":"")}>{displayMoney(x.amount)}</span></div>)}<div className="flex items-center justify-between pt-2 font-semibold"><span>Total Cost</span><span className="tabular">{displayMoney(result.total_cost)}</span></div></CardContent></Card></div>
    <section><div className="mb-4"><h2 className="text-lg font-semibold">怎么把这个活动变得更赚钱？</h2><p className="mt-1 text-sm text-slate-500">建议由确定性计算结果触发，不修改盈利引擎数字。</p></div><div className="grid gap-4 lg:grid-cols-3">{run.recommendations.slice(0,3).map((tip,i)=>{const Icon=tip.includes("物流")?Truck:tip.includes("达人")||tip.includes("佣金")?Users:tip.includes("售价")?TrendingUp:BadgeDollarSign; const kind=tip.includes("物流")?"shipping":tip.includes("达人")||tip.includes("佣金")?"creator":"price"; return <Card key={tip}><CardContent className="p-5"><div className="grid size-9 place-items-center rounded-lg bg-slate-100 text-slate-700"><Icon className="size-4"/></div><h3 className="mt-4 font-medium">{i===0?"优化利润安全边际":i===1?"控制关键成本":"降低叠加风险"}</h3><p className="mt-2 min-h-20 text-sm leading-6 text-slate-600">{tip}</p><Button className="mt-4 w-full" variant="outline" disabled={simulating} onClick={()=>void simulate(kind)}>{simulating?"正在重新计算":"模拟这个方案"}</Button></CardContent></Card>})}</div></section>
    <section><div className="mb-4"><h2 className="text-lg font-semibold">{run.scenarios.some((x)=>x.source==="calibrated")?(zh ? "本店铺实测场景" : "Measured shop scenarios"):(zh ? "成本敏感性" : "Cost sensitivity")}</h2><p className="mt-1 text-sm text-slate-500">{run.scenarios.some((x)=>x.source==="calibrated")?(zh ? "销量与退货率使用本店铺对账样本分位数。" : "Sales and return rates use your shop’s settlement quantiles."):(zh ? "以下变化直接由当前输入推导，不代表销量预测区间。" : "Changes come from your inputs; these are not sales forecast ranges.")}</p></div><div className="grid gap-4 md:grid-cols-3">{run.scenarios.map((x)=><Card key={x.name} className={cn(x.name==="基准"&&"border-slate-400")}><CardHeader className="pb-3"><div className="flex items-center justify-between"><CardTitle>{zh ? x.name : scenarioNameEn[x.name] ?? x.name}</CardTitle><Badge variant="outline" className={cn(x.profitable?"bg-emerald-50 text-emerald-700":"bg-red-50 text-red-700")}>{x.profitable?"仍然盈利":"转为亏损"}</Badge></div></CardHeader><CardContent><p className={cn("text-3xl font-semibold tabular",Number(x.total_profit)<0?"text-red-600":"text-slate-950")}>{displayMoney(x.total_profit)}</p><p className="mt-1 text-sm text-slate-500">利润率 {percent(x.profit_margin)}</p><p className="mt-1 text-xs text-amber-700">{x.source==="calibrated"?(zh ? `实测校准 · 样本 ${x.sample_size} 单` : `Calibrated · ${x.sample_size} orders`):(zh ? x.confidence_note : `No sales forecast range: ${x.sample_size ?? 0} orders are insufficient to estimate shop variability. Cost sensitivity only.`)}</p><Separator className="my-4"/><div className="grid grid-cols-3 gap-2 text-xs"><div><p className="text-slate-400">销量</p><p className="mt-1 font-medium">{quantity(Math.round(request.activity.estimated_sales*Number(x.sales_multiplier)))}</p></div><div><p className="text-slate-400">退货率</p><p className="mt-1 font-medium">{percent(x.return_rate)}</p></div><div><p className="text-slate-400">物流</p><p className="mt-1 font-medium">{percent(x.shipping_multiplier)}</p></div></div></CardContent></Card>)}</div></section>
    <Card><details><summary className="cursor-pointer list-none p-6 font-medium">详细计算过程 <span className="ml-2 text-xs font-normal text-slate-500">展开查看每项公式</span></summary><CardContent className="space-y-0 pt-0">{result.breakdown.map((x)=><div key={x.item} className="grid gap-1 border-t py-4 sm:grid-cols-[180px_1fr_120px]"><span className="text-sm font-medium">{x.item}</span><span className="text-sm text-slate-500">{x.formula}</span><span className="text-right text-sm font-semibold tabular">{displayMoney(x.amount)}</span></div>)}{result.assumptions.map((x)=><p key={x} className="mt-2 text-xs text-amber-700">假设：{x}</p>)}</CardContent></details></Card>
  </div>;
}

function AnalysisFlow() {
  const params = useSearchParams(); const { data, loading, error, refresh } = useData();
  const [step,setStep]=useState(1); const [productId,setProductId]=useState<number|null>(null); const [activityId,setActivityId]=useState<number|null>(null); const [activity,setActivity]=useState<PromotionActivity|null>(null); const [parsed,setParsed]=useState<ParsedPromotion|null>(null); const [text,setText]=useState(""); const [busy,setBusy]=useState(false); const [archiving,setArchiving]=useState(false); const [archiveError,setArchiveError]=useState<string|null>(null); const [run,setRun]=useState<AnalysisRun|null>(null); const [request,setRequest]=useState<ProfitAnalysisRequest|null>(null); const [search,setSearch]=useState(""); const [rateSource,setRateSource]=useState(""); const [rateDate,setRateDate]=useState(""); const [acceptedDemoDefaults,setAcceptedDemoDefaults]=useState(false); const loadedDemoRef=useRef<string|null>(null);
  const demoId=params.get("demo");
  useEffect(()=>{if(!data||!demoId||loadedDemoRef.current===demoId)return; const demo=data.cases.find((x)=>x.id===Number(demoId))??data.cases[Number(demoId)-1]; if(demo){loadedDemoRef.current=demoId;setProductId(demo.product_id);setActivityId(demo.id);setActivity(demo.request.activity);setRequest(demo.request);setStep(3);setRun(null);}},[data,demoId]);
  useEffect(()=>setAcceptedDemoDefaults(localStorage.getItem("cp-demo-defaults-accepted")==="true"),[]);
  const product=data?.products.find((x)=>x.id===productId)??null;
  const selectedConfig=product?.platform_configs.find((x)=>x.platform===activity?.platform)??null;
  const filtered=data?.products.filter((x)=>`${x.name} ${x.sku}`.toLowerCase().includes(search.toLowerCase()))??[];
  const updateActivity=(key:keyof PromotionActivity,value:string|number|null)=>setActivity((current)=>current?{...current,[key]:value}:current);
  const loadDemo=(item:DemoCase)=>{setProductId(item.product_id);setActivityId(item.id);setActivity(item.request.activity);setRequest(item.request);setParsed(null);setStep(3);};
  const parse=async()=>{setBusy(true);try{const value=await api.parsePromotion(text);setParsed(value);setActivity(value.activity);}finally{setBusy(false);}};
  const buildRequest=():ProfitAnalysisRequest|null=>{if(!product||!activity)return null;const config=product.platform_configs.find((x)=>x.platform===activity.platform);if(!config)return null;return {product:{name:product.name,sku:product.sku,category:product.category,purchase_cost:product.purchase_cost,packaging_cost:product.packaging_cost,weight_kg:product.weight_kg,volume_cm3:product.volume_cm3,currency:product.currency},platform_config:config,activity:{...activity,platform:config.platform,currency:product.currency},rate_source:rateSource||null,rate_effective_date:rateDate||null};};
  const analyze=async(next?:ProfitAnalysisRequest)=>{const payload=next??buildRequest();if(!payload)return;setBusy(true);setArchiveError(null);try{const value=await api.runAnalysis(payload);setRequest(payload);setRun(value);setStep(4);}finally{setBusy(false);}};
  const archive=async()=>{if(!request||!productId||run?.analysis_id)return;setArchiving(true);setArchiveError(null);try{const value=await api.archiveAnalysis(request,productId,activityId??undefined);if(!value.analysis_id)throw new Error("服务器没有返回归档编号");setActivityId(value.activity_id);setRun(value);await refresh();}catch(reason){setArchiveError(reason instanceof Error?reason.message:"归档失败，请稍后重试");}finally{setArchiving(false);}};
  if(loading)return <PageSkeleton/>; if(error||!data)return <ErrorState message={error??"数据为空"} retry={refresh}/>;
  return <div className="space-y-6"><Stepper current={step}/>
    {step===1&&<Card><CardHeader><CardTitle>选择要分析的商品</CardTitle><CardDescription>选择已有商品，平台成本会自动带入计算。</CardDescription></CardHeader><CardContent><div className="mb-5 flex flex-col gap-3 sm:flex-row"><Input value={search} onChange={(e)=>setSearch(e.target.value)} placeholder="搜索商品名称或 SKU"/><Button asChild variant="outline"><a href="/products">新增商品</a></Button></div><div className="grid gap-4 md:grid-cols-2 xl:grid-cols-3">{filtered.map((x)=><ProductCard key={x.id} product={x} selected={productId===x.id} onClick={()=>setProductId(x.id)}/>)}</div><div className="mt-6 flex justify-end"><Button disabled={!productId} onClick={()=>setStep(2)}>下一步：添加活动规则<ArrowRight className="size-4"/></Button></div></CardContent></Card>}
    {step===2&&<Card><CardHeader><CardTitle>添加活动规则</CardTitle><CardDescription>规则识别仅供辅助；请对照活动原文和店铺后台逐项核对费用、折扣与销量。</CardDescription></CardHeader><CardContent><Tabs defaultValue="text"><TabsList><TabsTrigger value="text">粘贴活动规则</TabsTrigger><TabsTrigger value="demo">演示案例</TabsTrigger></TabsList><TabsContent value="text" className="mt-6"><Textarea value={text} onChange={(e)=>setText(e.target.value)} className="min-h-40" placeholder="粘贴活动名称、折扣、佣金、活动时间和预计销量…"/><Button className="mt-3" disabled={!text||busy} onClick={()=>void parse()}><ScanSearch className="size-4"/>{busy?"正在识别":"识别活动规则"}</Button></TabsContent><TabsContent value="demo" className="mt-6 grid gap-3 lg:grid-cols-3">{data.cases.map((x)=><button key={x.id} onClick={()=>loadDemo(x)} className="rounded-xl border p-4 text-left hover:border-slate-400"><Badge variant="outline">{platformName(x.request.activity.platform)}</Badge><p className="mt-4 font-medium">{x.request.activity.activity_name}</p><p className="mt-2 text-xs text-slate-500">利润率 {percent(x.result.profit_margin)} · {x.result.risk_label}</p></button>)}</TabsContent></Tabs>
      {busy&&<div className="mt-6 grid gap-3 sm:grid-cols-3">{["正在读取活动规则","正在结构化关键字段","准备利润参数"].map((x,i)=><div key={x} className="rounded-lg border p-4"><div className="mb-3 h-1.5 overflow-hidden rounded-full bg-slate-100"><div className="h-full bg-blue-600" style={{width:`${(i+1)*28}%`}}/></div><p className="text-xs text-slate-500">{x}</p></div>)}</div>}
      {parsed&&<div className="mt-6 space-y-5"><div className="rounded-xl border p-5"><div className="flex items-center justify-between"><div><h3 className="font-medium">已识别 {Object.keys(parsed.recognized_fields).length} 项活动规则</h3><p className="mt-1 text-xs text-slate-500">系统不会猜测没有出现在规则中的费用。</p></div><span className="text-sm font-semibold tabular">{percent(parsed.activity.parse_confidence)}</span></div><Progress value={Number(parsed.activity.parse_confidence)*100} className="mt-4"/><div className="mt-5 grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{[["活动名称",activity?.activity_name],["平台",platformName(activity?.platform??"")],["活动折扣",percent(activity?.discount_value)],["预计销量",activity?.estimated_sales]].map(([a,b])=><div key={String(a)} className="rounded-lg bg-slate-50 p-3"><p className="text-xs text-slate-500">{a}</p><p className="mt-1 truncate text-sm font-medium">{String(b)}</p></div>)}</div></div>{parsed.missing_suggestions.length>0&&<div className="rounded-xl border border-amber-200 bg-amber-50/40 p-5"><h3 className="font-medium">还有 {parsed.missing_suggestions.length} 项信息会影响利润结果</h3><div className="mt-4 grid gap-3 lg:grid-cols-2">{parsed.missing_suggestions.map((x)=><div key={x.field} className="rounded-lg border bg-white p-4"><div className="flex items-center justify-between"><p className="text-sm font-medium">{x.label}</p><Badge variant="outline" className="text-amber-700">需要确认</Badge></div><p className="mt-2 text-xs leading-5 text-slate-500">{x.reason}</p>{["discount_value","extra_commission_rate","creator_commission_rate","return_rate_override"].includes(x.field)?<Input className="mt-3" type="number" placeholder="按卖家实际承担填写 %" onChange={(e)=>updateActivity(x.field as keyof PromotionActivity,String(Number(e.target.value)/100))}/>:x.field==="estimated_sales"?<Input className="mt-3" type="number" placeholder="100" onChange={(e)=>updateActivity("estimated_sales",Number(e.target.value))}/>:null}<p className="mt-2 text-[11px] text-slate-400">跳过时：{x.default_action}</p></div>)}</div></div>}<div className="flex justify-between"><Button variant="ghost" onClick={()=>setStep(1)}><ArrowLeft className="size-4"/>返回</Button><Button onClick={()=>setStep(3)}>确认识别结果<ArrowRight className="size-4"/></Button></div></div>}
      {!parsed&&<div className="mt-6 flex justify-between"><Button variant="ghost" onClick={()=>setStep(1)}><ArrowLeft className="size-4"/>返回</Button></div>}
    </CardContent></Card>}
    {step===3&&product&&activity&&<Card><CardHeader><CardTitle>确认影响利润的关键参数</CardTitle><CardDescription>系统已经带入可计算的参数。确认无误后可直接开始分析。</CardDescription></CardHeader><CardContent>{!selectedConfig&&<Alert className="mb-6"><AlertTriangle className="size-4"/><AlertTitle>缺少对应平台费用配置</AlertTitle><AlertDescription>请先在商品管理中为这个商品添加 {platformName(activity.platform)} 配置，再回来分析。系统不会借用其他平台的费率。</AlertDescription><Button asChild className="mt-3" variant="outline" size="sm"><a href="/products">去添加平台配置</a></Button></Alert>}{selectedConfig?.demo_default&&!acceptedDemoDefaults&&<div className="mb-6 flex flex-col gap-4 rounded-2xl bg-blue-50/75 p-5 sm:flex-row sm:items-center sm:justify-between"><div className="flex gap-3"><span className="grid size-9 shrink-0 place-items-center rounded-full bg-blue-100 text-blue-700"><Sparkles className="size-4"/></span><div><p className="text-sm font-semibold text-slate-900">当前已自动使用演示费率</p><p className="mt-1 max-w-2xl text-xs leading-5 text-slate-600">这不是错误，也不会阻止分析。你可以使用页面下方当前数值继续；如果已有店铺实际费率，可前往商品管理修改后再分析。</p></div></div><div className="flex shrink-0 gap-2"><Button asChild variant="outline" size="sm"><a href="/products">修改实际费率</a></Button><Button size="sm" onClick={()=>{localStorage.setItem("cp-demo-defaults-accepted","true");setAcceptedDemoDefaults(true);}}>使用当前费率</Button></div></div>}<div className="grid gap-5 sm:grid-cols-2 lg:grid-cols-4">{[
      ["活动折扣 (%)","discount_value",Number(activity.discount_value)*100],["预计销量","estimated_sales",activity.estimated_sales],["活动额外佣金 (%)","extra_commission_rate",Number(activity.extra_commission_rate)*100],["达人佣金 (%)","creator_commission_rate",Number(activity.creator_commission_rate??0)*100],["卖家物流 / 单","seller_shipping_cost",Number(activity.seller_shipping_cost??product.platform_configs.find(x=>x.platform===activity.platform)?.shipping_cost??0)],["退货率 (%)","return_rate_override",Number(activity.return_rate_override??product.platform_configs.find(x=>x.platform===activity.platform)?.return_rate??0)*100],["平台补贴 / 单","platform_subsidy",Number(activity.platform_subsidy)],["固定活动投入","ad_budget",Number(activity.ad_budget)],
      ].map(([label,key,value])=><label key={String(key)} className="space-y-2 text-sm"><span className="text-slate-600">{String(label)}</span><Input type="number" value={Number(value)} onChange={(e)=>{const raw=Number(e.target.value);updateActivity(key as keyof PromotionActivity,["discount_value","extra_commission_rate","creator_commission_rate","return_rate_override"].includes(String(key))?String(raw/100):key==="estimated_sales"?raw:String(raw));}}/></label>)}</div>

      <div className="mt-6 grid gap-4 sm:grid-cols-2"><label className="space-y-2 text-sm"><span>费率来源</span><Input value={rateSource} onChange={(e)=>setRateSource(e.target.value)} placeholder="店铺协议、Seller Center 页面或复核说明" /></label><label className="space-y-2 text-sm"><span>费率生效日期</span><Input type="date" value={rateDate} onChange={(e)=>setRateDate(e.target.value)} /></label></div>
      <div className="mt-7 flex justify-between"><Button variant="ghost" onClick={()=>setStep(2)}><ArrowLeft className="size-4"/>返回规则</Button><Button disabled={busy||!selectedConfig} onClick={()=>void analyze()}>{busy?"正在拆解成本假设":"开始盈利分析"}<ArrowRight className="size-4"/></Button></div></CardContent></Card>}
    {step===4&&run&&request&&<><div className="flex items-center justify-between"><Button variant="ghost" onClick={()=>setStep(3)}><ArrowLeft className="size-4"/>调整参数</Button><Badge variant="outline" className="bg-white">活动分析 / {request.activity.activity_name}</Badge></div><AnalysisResultView run={run} request={request} rerun={analyze} archive={archive} archiving={archiving} archiveError={archiveError}/></>}
  </div>;
}

export default function AnalysisPage(){return <Suspense fallback={<PageSkeleton/>}><AnalysisFlow/></Suspense>}
