"use client";

import { AlertTriangle, Award, BarChart3, ShoppingCart } from "lucide-react";
import { Bar, BarChart, CartesianGrid, Cell, ResponsiveContainer, Tooltip, XAxis, YAxis } from "recharts";
import { useData } from "@/components/data-provider";
import { EmptyState, ErrorState, PageSkeleton, RiskBadge } from "@/components/common";
import { Badge } from "@/components/ui/badge";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@/components/ui/table";
import { money, percent, platformName, quantity } from "@/lib/utils";
import { useState } from "react";

export default function ComparisonPage(){
  const {data,loading,error,refresh}=useData(); const [productId,setProductId]=useState<string>("");
  if(loading)return <PageSkeleton/>; if(error||!data)return <ErrorState message={error??"数据为空"} retry={refresh}/>;
  const selected=Number(productId||data.products[0]?.id); const cases=data.cases.filter((x)=>x.product_id===selected).sort((a,b)=>Number(b.result.estimated_total_profit)-Number(a.result.estimated_total_profit));
  const best=cases[0], highest=[...cases].sort((a,b)=>b.request.activity.estimated_sales-a.request.activity.estimated_sales)[0];
  return <div className="space-y-6"><Card><CardContent className="flex flex-col justify-between gap-4 p-5 sm:flex-row sm:items-center"><div><p className="text-sm font-medium">选择比较商品</p><p className="mt-1 text-xs text-slate-500">同一商品的不同平台活动将按相同利润口径排序。</p></div><Select value={String(selected)} onValueChange={(value)=>value&&setProductId(value)}><SelectTrigger className="w-full sm:w-72"><SelectValue/></SelectTrigger><SelectContent>{data.products.map((x)=><SelectItem key={x.id} value={String(x.id)}>{x.name} · {x.sku}</SelectItem>)}</SelectContent></Select></CardContent></Card>
  {!cases.length?<EmptyState title="暂无可比较活动" description="为该商品添加至少一个活动后，即可进行横向比较。"/>:<><div className="grid gap-4 lg:grid-cols-2"><Card className="border-emerald-200"><CardContent className="p-6"><div className="flex items-center gap-2 text-sm text-emerald-700"><Award className="size-4"/>最佳选择</div><h2 className="mt-4 text-xl font-semibold">{best.request.activity.activity_name}</h2><p className="mt-1 text-sm text-slate-500">{platformName(best.request.activity.platform)}</p><div className="mt-5 flex gap-8"><div><p className="text-xs text-slate-500">利润率</p><p className="mt-1 text-2xl font-semibold tabular">{percent(best.result.profit_margin)}</p></div><div><p className="text-xs text-slate-500">预计总利润</p><p className="mt-1 text-2xl font-semibold text-emerald-700 tabular">{money(best.result.estimated_total_profit)}</p></div></div></CardContent></Card><Card className={Number(highest.result.unit_profit)<0?"border-red-200":""}><CardContent className="p-6"><div className="flex items-center gap-2 text-sm text-slate-600"><ShoppingCart className="size-4"/>最高销量</div><h2 className="mt-4 text-xl font-semibold">{highest.request.activity.activity_name}</h2><p className="mt-1 text-sm text-slate-500">预计 {quantity(highest.request.activity.estimated_sales)} 单</p><div className="mt-5 flex items-center gap-3">{Number(highest.result.unit_profit)<0&&<AlertTriangle className="size-5 text-red-600"/>}<p className={Number(highest.result.unit_profit)<0?"font-medium text-red-600":"font-medium text-slate-700"}>销量最高 ≠ 最赚钱 · {money(highest.result.estimated_total_profit)}</p></div></CardContent></Card></div>
  <Card><CardHeader><CardTitle>活动利润对比</CardTitle><CardDescription>排名首先依据预计总利润，再参考利润率与单件安全边际。</CardDescription></CardHeader><CardContent className="scrollbar-subtle overflow-x-auto"><Table><TableHeader><TableRow><TableHead>排名</TableHead><TableHead>平台</TableHead><TableHead>活动</TableHead><TableHead>活动价</TableHead><TableHead>利润 / 单</TableHead><TableHead>利润率</TableHead><TableHead>预计销量</TableHead><TableHead>预计总利润</TableHead><TableHead>风险</TableHead></TableRow></TableHeader><TableBody>{cases.map((x,i)=><TableRow key={x.id} className={i===0?"bg-emerald-50/40":""}><TableCell><Badge variant={i===0?"default":"outline"}>#{i+1}{i===0&&" Best Profit"}</Badge></TableCell><TableCell><Badge variant="outline">{platformName(x.request.activity.platform)}</Badge></TableCell><TableCell className="font-medium">{x.request.activity.activity_name}</TableCell><TableCell>{money(x.result.selling_price)}</TableCell><TableCell className={Number(x.result.unit_profit)<0?"text-red-600":"text-emerald-700"}>{money(x.result.unit_profit)}</TableCell><TableCell>{percent(x.result.profit_margin)}</TableCell><TableCell>{quantity(x.result.estimated_sales)}</TableCell><TableCell className="font-medium">{money(x.result.estimated_total_profit)}</TableCell><TableCell><RiskBadge level={x.result.risk_level}/></TableCell></TableRow>)}</TableBody></Table></CardContent></Card>
  <Card><CardHeader><CardTitle>预计总利润</CardTitle><CardDescription>盈利与亏损方向一眼可见</CardDescription></CardHeader><CardContent className="h-80"><ResponsiveContainer><BarChart data={cases.map(x=>({name:x.request.activity.activity_name.replace("TikTok ",""),value:Number(x.result.estimated_total_profit)}))}><CartesianGrid vertical={false} stroke="#e2e8f0"/><XAxis dataKey="name" axisLine={false} tickLine={false}/><YAxis axisLine={false} tickLine={false}/><Tooltip formatter={(v)=>money(Number(v))}/><Bar dataKey="value" radius={[5,5,0,0]}>{cases.map(x=><Cell key={x.id} fill={Number(x.result.estimated_total_profit)<0?"#dc2626":"#16a34a"}/>)}</Bar></BarChart></ResponsiveContainer></CardContent></Card></>}
  </div>;
}
